version: '3'

services:
  weather:
    image: weather
    build:
      context: ./services/weather
    expose:
      - 50051
    depends_on:
      - redis
    environment: 
      NODE_ENV: development
      PORT: 50051
      REDIS_PORT: 6379
      REDIS_HOST: 'redis'
      WEATHER_APIKEY: 'ba7f2324737e426236bdf6cccd9d2346'
      WEATHER_APIURL: 'https://api.openweathermap.org/data/2.5'

    # restart: on-failure
    
  gateway:
    image: gateway
    build:
      context: ./services/gateway
    ports:
      - 8080:8080
    depends_on: 
      - weather
      - redis
    environment: 
      NODE_ENV: 'development'
      PORT: 8080
      REDIS_PORT: 6379
      REDIS_HOST: 'redis'
    # restart: on-failure

  redis:
    image: bitnami/redis:latest
    container_name: redis_container
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    volumes:
      - redis_data:/bitnami/redis
    ports:
      - 6379:6379

volumes: 
  redis_data:

    

